version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050323365.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t flask-app-task-ecr:latest .
      - docker tag flask-app-task-ecr:latest 975050323365.dkr.ecr.us-east-1.amazonaws.com/flask-app-task-ecr:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 975050323365.dkr.ecr.us-east-1.amazonaws.com/flask-app-task-ecr:latest
      - echo Writing image definitions file...
      - printf '[{"name":"flask-app","imageUri":"975050323365.dkr.ecr.us-east-1.amazonaws.com/flask-app-task-ecr:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
